filename_train: "All_data.csv"
filename_val: "file1_RT_100.csv"
med_config: "/kaggle/working/med_config.json"
device: 'cuda'
image_root: '/kaggle/input/mmm-dataset/Image_all/Image_all'
ann_root: '/kaggle/working/'
dataset: 'mmm_rt'
pretrained: 'https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_base_retrieval_coco.pth'
output_dir: '/kaggle/working/'
vit: 'base'
batch_size_train: 8
batch_size_test: 4
vit_grad_ckpt: True
vit_ckpt_layer: 4
init_lr: 0.00003
image_size: 384
queue_size: 57600
alpha: 0.4
k_test: 20
negative_all_rank: True
weight_decay: 0.05
min_lr: 0
max_epoch: 12